---
#For Ubuntu Trusty, Wily, and Xenial, it’s recommended to install the linux-image-extra kernel package.
#The linux-image-extra package allows you use the aufs storage driver.
- name: Docker | CE | Ubuntu | Install the linux-image-extra kernal package
  apt: name="linux-image-extra-{{ ansible_kernel }}" state=present
  when: ansible_distribution_version in ['14.04','15.10']

#If you are installing on Ubuntu 14.04 or 12.04, apparmor is required.
- name: Docker | CE | Ubuntu | Install AppArmor Dependency
  apt: name=apparmor state=present
  when: ansible_distribution_version in ['14.04','12.04']

#Before we start docker, we need to make sure the system is running on Kernel 3.13 or higher.
- name: Docker | CE | Ubuntu | Update Kernel Version to >= 3.13 | Reboot Host
  command: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: ansible_distribution_version == '12.04'

- name: Docker | CE | Ubuntu | Update Kernel Version to at least 3.13 | Wait for Host
  local_action: wait_for host="{{ inventory_hostname }}" state=started delay=30 timeout=300
  become: false
  when: ansible_distribution_version == '12.04'

- name: Docker | CE | APT | Add Docker GPG Key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

#Docker’s APT repository contains Docker 1.7.1 and higher.
- name: Docker | CE | APT | Configure Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Docker | CE | APT | Enable Edge repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} edge"
    state: present
  when: docker_channel == "edge"
