---
dist: trusty
sudo: required
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: docker
  matrix:
    - MOLECULE_DISTRO: centos:6
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_SERVICE_MANAGER: systemd
    - MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: fedora:26
    - MOLECULE_DISTRO: fedora:27
    - MOLECULE_DISTRO: fedora:28
    - MOLECULE_DISTRO: fedora:29
    - MOLECULE_DISTRO: opensuse/leap:15
    - MOLECULE_DISTRO: opensuse/leap:42
    - MOLECULE_DISTRO: ubuntu:trusty
    - MOLECULE_DISTRO: ubuntu:xenial
    - MOLECULE_DISTRO: ubuntu:bionic
    - MOLECULE_DISTRO: debian:wheezy
    - MOLECULE_DISTRO: debian:jessie
    - MOLECULE_DISTRO: debian:stretch

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME avinetworks.$ROLE_NAME
  - cd avinetworks.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
