---
# tasks file for avinetworks.docker
- name: Docker | Include Specific Variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Docker | Start Installation
  include: "{{ ansible_pkg_mgr }}.yml"

- name: Docker | Storage Driver
  include: "storage_drivers/{{ docker_storage_driver }}.yml"
  when: docker_storage_driver is defined

- name: Docker | Ensure docker starts at Boot
  service: name=docker enabled=yes

- name: Docker | Set the docker configuration
  set_fact:
    docker_config: "{{ lookup('template', 'docker_config.j2') | from_yaml }}"

- name: Docker | Deploy Config
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json
  when: docker_config != ""
  notify: Docker | Restart Docker
  
- name: Docker | Proxy configuration
  include: proxy.yml
  when: docker_http_proxy is defined
