---
- name: Docker | Daemon-reload
  shell: systemctl daemon-reload

- name: Docker | Restart Docker
  service: name=docker state=restarted

- name: Docker | CE | APT | Upgrade to Edge
  apt: name=docker-ce state=latest

- name: Docker | CE | YUM | Upgrade to Edge
  yum: name=docker-ce state=latest
