---
- name: Docker | CE | APT | Remove old repo lxc-docker
  apt:
    name:
      - docker
      - docker-engine
      - docker-io
    state: absent

- name: Docker | CE | APT | Install Prerequisits for APT
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
    state: present

- name: Docker | CE | APT | Perform specific os tasks
  include: os/{{ ansible_distribution|lower }}.yml

- name: Docker | CE | APT | Add Docker GPG Key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"
    validate_certs: "{{ docker_apt_key_validate_certs }}"

- name: Docker | CE | APT | Configure Docker repository
  apt_repository:
    repo: "{{ docker_apt_repo_url }}"

- name: Docker | CE | APT | Enable Edge repository
  apt_repository:
    repo: "{{ docker_apt_repo_url_edge }}"
  when: docker_channel == "edge"

- name: Docker | CE | APT | Install docker-ce
  apt: name=docker-ce state=present
  notify: Docker | Restart Docker
