---

- name: Docker | CE | DNF | Add repository key
  rpm_key:
    key: "{{ docker_ce_gpg_key }}"
  register: docker_ce_import_rpm_key
  ignore_errors: true

- name: Docker | CE | DNF | Add repository key (systems without SNI)
  block:
    - name: Docker | CE | DNF | Ensure curl is present (systems without SNI).
      package: name=curl
    - name: Docker | CE | DNF | Download GPG key (systems without SNI).
      shell: "curl -sSL {{ docker_ce_gpg_key }} -o /tmp/docker-gpg"
    - name: Docker | CE | DNF | Add Docker GPG key (systems without SNI).
      shell: rpm --import /tmp/docker-gpg
    - name: Docker | CE | DNF | Remove docker-gpg from tmp folder
      file: path=/tmp/docker-gpg state=absent
  when: docker_ce_import_rpm_key is failed

- name: Docker | CE | DNF | Deploy repository
  get_url:
    url: "{{ docker_ce_repo_file_url }}"
    dest: /etc/dnf.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  register: docker_ce_add_repo
  ignore_errors: true

- name: Docker | CE | DNF | Deploy repository (systems without SNI)
  block:
    - name: Docker | CE | DNF | Install dnf-utils (systems without SNI)
      dnf: name=dnf-plugins-core
    - name: Docker | CE | DNF | Deploy repository (systems without SNI)
      shell: "dnf config-manager --add-repo {{ docker_ce_repo_file_url }}"
      args:
        creates: /etc/dnf.repos.d/docker-ce.repo
  when: docker_ce_add_repo is failed

- name: Docker | CE | DNF | Enable edge repository
  dnf_repository:
    name: docker-ce-edge
    description: "Docker CE Edge - $basearch"
    baseurl: "{{ docker_ce_edge_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ docker_ce_gpg_key }}"
    enabled: yes
    file: docker-ce
  when: docker_channel == "edge"

- name: Docker | CE | DNF | Perform specific os tasks
  include_tasks: os/{{ ansible_distribution|lower }}.yml

# - name: Docker | CE | DNF | Remove older Docker installations
#   dnf: name={{ item }} state=absent
#   with_items:
#     - docker
#     - docker-common
#     - docker-engine

- name: Docker | CE | DNF | Install docker-ce
  dnf:
    name: docker-ce
    state: present
  notify: Docker | Restart Docker
