---
- name: Docker | CE | YUM | Deploy repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Docker | CE | YUM | Enable edge repository
  yum_repository:
    name: docker-ce-edge
    description: "Docker CE Edge - $basearch"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/edge"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    file: docker-ce
  when: docker_channel == "edge"

- name: Docker | CE | YUM | Perform specific os tasks
  include_tasks: os/{{ ansible_distribution|lower }}.yml

# - name: Docker | CE | YUM | Remove older Docker installations
#   yum: name={{ item }} state=absent
#   with_items:
#     - docker
#     - docker-common
#     - docker-engine

- name: Docker | CE | YUM | Install docker-ce
  yum:
    name: docker-ce
    state: present
  notify: Docker | Restart Docker
