---

- name: Docker | CE | YUM | Add repository key
  rpm_key:
    key: "{{ docker_ce_gpg_key }}"
  register: docker_ce_import_rpm_key
  ignore_errors: true

- name: Docker | CE | YUM | Add repository key (systems without SNI)
  block:
    - name: Docker | CE | YUM | Ensure curl is present (systems without SNI).
      package: name=curl
    - name: Docker | CE | YUM | Download GPG key (systems without SNI).
      shell: "curl -sSL {{ docker_ce_gpg_key }} -o /tmp/docker-gpg"
    - name: Docker | CE | YUM | Add Docker GPG key (systems without SNI).
      shell: rpm --import /tmp/docker-gpg
    - name: Docker | CE | YUM | Remove docker-gpg from tmp folder
      file: path=/tmp/docker-gpg state=absent
  when: docker_ce_import_rpm_key is failed

- name: Docker | CE | YUM | Deploy repository
  get_url:
    url: "{{ docker_ce_repo_file_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  register: docker_ce_add_repo
  ignore_errors: true

- name: Docker | CE | YUM | Deploy repository (systems without SNI)
  block:
    - name: Docker | CE | YUM | Install yum-utils (systems without SNI)
      yum: name=yum-utils
    - name: Docker | CE | YUM | Deploy repository (systems without SNI)
      shell: "yum-config-manager --add-repo {{ docker_ce_repo_file_url }}"
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
  when: docker_ce_add_repo is failed

- name: Docker | CE | YUM | Enable edge repository
  yum_repository:
    name: docker-ce-edge
    description: "Docker CE Edge - $basearch"
    baseurl: "{{ docker_ce_edge_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ docker_ce_gpg_key }}"
    enabled: yes
    file: docker-ce
  when: docker_channel == "edge"

- name: Docker | CE | YUM | Perform specific os tasks
  include_tasks: os/{{ ansible_distribution|lower }}.yml

# - name: Docker | CE | YUM | Remove older Docker installations
#   yum: name={{ item }} state=absent
#   with_items:
#     - docker
#     - docker-common
#     - docker-engine

- name: Docker | CE | YUM | Install docker-ce
  yum:
    name: docker-ce
    state: present
  notify: Docker | Restart Docker
