---
- name: Docker | Storage Driver | devicemapper | Install LVM2 | YUM
  yum: name=lvm2 state=present
  when: ansible_pkg_mgr == 'yum'

- name: Docker | Storage Driver | devicemapper | Install LVM2 | DNF
  dnf: name=lvm2 state=present
  when: ansible_pkg_mgr == 'dnf'

- name: Docker | Storage Driver | devicemapper | Install LVM2 | APT
  apt: name=lvm2 state=present
  when: ansible_pkg_mgr == 'dnf'

- name: Docker | Storage Driver | devicemapper | Configure logical volume group
  lvg: vg=docker pvs="{{ block_device }}"

- name: Docker | Storage Driver | devicemapper | Create thinpool volume
  lvol: vg=docker lv=thinpool size=95%VG opts="--wipesignatures y"
  register: thinpool

- name: Docker | Storage Driver | devicemapper | Create thinpoolmeta volume
  lvol: vg=docker lv=thinpoolmeta size=1%VG opts="--wipesignatures y"

- name: Docker | Storage Driver | devicemapper | Convert volumes to thinpool
  shell: lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
  when: thinpool.changed

- name: Docker | Storage Driver | devicemapper | Configure autoextension of thin pools via 'lvm' profile
  copy: src=docker-thinpool.profile dest=/etc/lvm/profile/docker-thinpool.profile
  register: docker_thinpool_profile
  notify: Docker | Restart Docker

- name: Docker | Storage Driver | devicemapper | Apply 'lvm' profile
  shell: lvchange --metadataprofile docker-thinpool docker/thinpool
  when: docker_thinpool_profile.changed

- name: Docker | Storage Driver | devicemapper | Make sure /etc/docker is Created
  file: path=/etc/docker state=directory

- name: Docker | Storage Driver | devicemapper | Configure daemon
  copy: src=daemon.json dest=/etc/docker/daemon.json
  notify: Docker | Restart Docker
